[project]
name = "erc1155-audit"
authors = ["Security Research Team"]
description = "Comprehensive ERC1155 smart contract security audit framework"
telemetry = false
requirements = []

[contracts.token-validator]
path = "contracts/token-validator.clar"
depends_on = []

[contracts.permission-manager]
path = "contracts/permission-manager.clar"
depends_on = []

[contracts.transfer-analysis]
path = "contracts/transfer-analysis.clar"
depends_on = []

[contracts.security-metrics]
path = "contracts/security-metrics.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = true
